### PR TITLE
Change the default value of NoFontScaling to 1

### PR DESCRIPTION
**Pull request by seri14**
because I met many users that happened troubles by this.
and output key/value to support users who need it.

### CODE REVIEW

**Comment by crosire** [comment]
I'm confused as to how this can cause trouble. It only scales as long as the UI is open. And it's explicitly mentioned in the tutorial on first startup, so disabling would be contradicting that.

**Comment by seri14** [comment]
I'm confused too.
If all users read it or fully remember it by not required users, I have not wrote this. who press the [Restart Tutorial] button when scaled?

**Comment by Mortalitas** [comment]
I'll second what Seri is pointing out here, many end users, both those who have completed the tutorial and those who have not (by means of alternative distributions or otherwise), find the feature to be more of a nuisance than a benefit.

Having the scale "locked" (in this case, hotkeys off) by default benefits the majority who will never actually use the feature but may be bewildered when accidentally triggering it.

**Comment by seri14** [comment]
Well, about alternative distributions, It have no problems there. but not touch the default value of TutorialProgress.
and distributor should can completely avoid this problem.

**Comment by crosire** [comment]
Well at least have it enabled by default, and disable it once the tutorial was finished. Then it's no longer a nuisance for those users that cannot read, but is still there to scale the windows during the tutorial.

**Pull request closed without merging**
