### PR TITLE
Change error check and display condition of screenshot path

### PR DESCRIPTION
**Pull request by seri14**

### CODE REVIEW

**Comment by seri14** [comment]
Why does the user have to open the home tab for error checking when modied path?

**Comment by Bluscream** [comment]
Why not just create the path if it does not exist?

**Comment by seri14** [comment]
This change (and original pull request) is particularly effective because notify error when got ReShade.ini from friends or internet.

**Comment by seri14** [comment]
Description of #76 included "folder structure changed", but lost it.

**Comment by seri14** [comment]
@Bluscream I think good to make pull request or post to forum.

**Pull request closed without merging**
