### PR TITLE
Support unicode character set for the path

### PR DESCRIPTION
**Pull request by seri14**
From case: https://twitter.com/SkylarTnT/status/1093440629701595142

Avoided setting types changes to `std::wstring`.

### CODE REVIEW

**Comment by crosire** [comment]
`std::wstring_convert()` is deprecated in C++17 hence why it was removed in previous commits. There is however `std::filesystem::u8path()` which can be used to construct a `std::filesystem::path` from a UTF-8 sequence.

**Comment by crosire** [comment]
There already is a UTF8-UTF16 converter in the ReShade codebase. Check deps/utfcpp.

**Comment by seri14** [comment]
Why not used it

**Comment by seri14** [comment]
thrown in the trash by very easy reason

**Comment by seri14** [comment]
If you have answer to solve a clear way, you should teach it to me. I am not playing quiz game. I am not want waste of time.

**Comment by crosire** [comment]
I told you a way to do it in one line: https://en.cppreference.com/w/cpp/filesystem/path/u8path ... Not hiding anything. deps/utfcpp is not even needed here. I just didn't understand why you would add another unicode parser if there already is one in.

**Comment by seri14** [comment]
I noticed it now. I am sorry I misunderstood your comment.

**Pull request merged**
