### PR TITLE
Add history window

### PR DESCRIPTION
**Pull request by seri14**
https://user-images.githubusercontent.com/71371622/148185503-03b408a6-c3dd-4dde-a2f9-ac44c26a1215.mp4

### CODE REVIEW

**Comment by crosire** [comment]
I think this would be perfect as an add-on (since the add-on API already lets you create additional windows). Let me see if I can extend the add-on API enough to get this running this way (by adding some more events that get called when uniforms/techniques/... change).

**Comment by crosire** [comment]
With 9c9394fb18c8ec328bbb9e760f66291d3eab2a79 this can now be implemented as an add-on:
```c++
#include <imgui.h>
#include <reshade.hpp>
#include <vector>
#include <string>
#include <list>
#include <algorithm>

union uniform_data
{
	bool as_bool;
	float as_float[16];
	int32_t as_int[16];
	uint32_t as_uint[16];
};

struct history
{
	enum class kind { variable = 0, technique_switch } kind = history::kind::variable;
	std::string technique_name;
	reshade::api::effect_technique technique_index = { 0 };
	bool technique_enabled = false;
	reshade::api::effect_uniform_variable variable_index = { 0 };
	uniform_data before = {}, after = {};
	bool confirmed = false;
	std::vector<std::string> technique_names_before, technique_names_after;
};

struct __declspec(uuid("EE32DAA4-6B5C-47E6-9409-F87CCA0E5797")) history_context
{
	bool _show_edit_history = false;
	std::vector<std::string> _technique_names;

	size_t _history_limit = 1000;
	std::list<history> _histories;
	bool _history_updated = false;
	size_t _history_position = 0;
};

static void on_init(reshade::api::effect_runtime *runtime)
{
	runtime->create_private_data<history_context>();
}
static void on_destroy(reshade::api::effect_runtime *runtime)
{
	runtime->destroy_private_data<history_context>();
}

static void on_reloaded_effects(reshade::api::effect_runtime *runtime)
{
	auto &ctx = runtime->get_private_data<history_context>();

	ctx._histories.clear();
	ctx._history_position = 0;
	ctx._history_updated = false;
}

static bool on_set_uniform_value(reshade::api::effect_runtime *runtime, reshade::api::effect_uniform_variable variable, const void *value, size_t size)
{
	char ui_type[16] = ""; size_t ui_type_len = sizeof(ui_type);
	runtime->get_uniform_annotation_value(variable, "ui_type", ui_type, &ui_type_len);
	if (ui_type_len == 0)
		return false;

	auto &ctx = runtime->get_private_data<history_context>();

	reshade::api::format basetype;
	runtime->get_uniform_variable_type(variable, &basetype);

	uniform_data before = {}, after = {};

	switch (basetype)
	{
	case reshade::api::format::r32_typeless:
		runtime->get_uniform_value(variable, &before.as_bool, 1);
		break;
	case reshade::api::format::r32_sint:
		runtime->get_uniform_value(variable, before.as_int, 16);
		break;
	case reshade::api::format::r32_uint:
		runtime->get_uniform_value(variable, before.as_uint, 16);
		break;
	case reshade::api::format::r32_float:
		runtime->get_uniform_value(variable, before.as_float, 16);
		break;
	}

	std::memcpy(after.as_uint, value, std::min(size, size_t(4 * 16)));

	if (std::memcmp(&before, &after, sizeof(after)) != 0)
	{
		history history;
		history.kind = history::kind::variable;
		history.variable_index = variable;
		history.before = before;
		history.after = after;

		for (; ctx._history_position > 0; --ctx._history_position)
			ctx._histories.pop_front();
		if (ctx._histories.emplace_front(std::move(history)); ctx._histories.size() > ctx._history_limit)
			ctx._histories.resize(ctx._history_limit);

		ctx._history_position = 0;
		ctx._history_updated = true;
	}

	return false;
}

static bool on_set_technique_enabled(reshade::api::effect_runtime *runtime, reshade::api::effect_technique technique, bool status)
{
	auto &ctx = runtime->get_private_data<history_context>();

	char technique_name[128] = ""; size_t technique_name_len = sizeof(technique_name);
	runtime->get_technique_name(technique, technique_name, &technique_name_len);

	auto it = std::next(ctx._histories.begin(), ctx._history_position);

	enum class condition { pass, add, backward };
	condition condition = condition::pass;

	if (it == ctx._histories.end())
		condition = condition::add;
	else if (it->kind != history::kind::technique_switch)
		condition = condition::add;
	else if (it->technique_name != technique_name)
		condition = condition::add;
	else if (status != it->technique_enabled)
		condition = condition::backward;
	else
		condition = condition::add;

	if (condition == condition::add)
	{
		history history;
		history.kind = history::kind::technique_switch;
		history.technique_name = technique_name;
		history.technique_index = technique;
		history.technique_enabled = status;

		for (; ctx._history_position > 0; --ctx._history_position)
			ctx._histories.pop_front();
		if (ctx._histories.emplace_front(std::move(history)); ctx._histories.size() > ctx._history_limit)
			ctx._histories.resize(ctx._history_limit);
	}
	else if (condition == condition::backward)
	{
		++ctx._history_position;
	}

	return false;
}

static void draw_history_window(reshade::api::effect_runtime *runtime)
{
	auto &ctx = runtime->get_private_data<history_context>();

	size_t selection = std::numeric_limits<size_t>::max();
	if (ImGui::Selectable("End of Undo", ctx._history_position == ctx._histories.size()))
		selection = ctx._histories.size();

	if (ctx._histories.empty())
		return;

	bool modified = false;

	std::string s; s.resize(80);
	std::string str;

	size_t position = ctx._histories.size() - 1;
	for (auto it = ctx._histories.rbegin(); it != ctx._histories.rend(); --position, ++it)
	{
		if (it->kind == history::kind::technique_switch)
		{
			str += it->technique_name;
			str += it->technique_enabled ? " True" : " False";
		}
		else
		{
			char ui_type[16] = ""; size_t ui_type_len = sizeof(ui_type);
			runtime->get_uniform_annotation_value(it->variable_index, "ui_type", ui_type, &ui_type_len);

			char variable_name[128] = ""; size_t variable_name_len = sizeof(variable_name);
			runtime->get_uniform_variable_name(it->variable_index, variable_name, &variable_name_len);

			str += variable_name;

			reshade::api::format basetype;
			unsigned int rows;
			runtime->get_uniform_variable_type(it->variable_index, &basetype, &rows);

			for (unsigned int i = 0; rows > i; ++i)
			{
				if (basetype == reshade::api::format::r32_float)
				{
					if (strcmp(ui_type, "color") == 0)
					{
						str.append(s.data(), ::_snprintf(s.data(), s.size(), " %c %+0.0f (%0.0f)", "RGBA"[i], (it->after.as_float[i] - it->before.as_float[i]) / (1.0f / 255.0f), it->after.as_float[i] / (1.0f / 255.0f)));
					}
					else
					{
						float ui_stp_val = 0.0f;
						runtime->get_uniform_annotation_value(it->variable_index, "ui_step", &ui_stp_val, 1);
						if (FLT_EPSILON > ui_stp_val)
							ui_stp_val = 0.001f;

						// Calculate display precision based on step value
						int precision = 0;
						for (float x = 1.0f; x * ui_stp_val < 1.0f && precision < 9; x *= 10.0f)
							++precision;

						str.append(s.data(), ::_snprintf(s.data(), s.size(), " %c %+0.*f (%0.*f)", "XYZW"[i], precision, it->after.as_float[i] - it->before.as_float[i], precision, it->after.as_float[i]));
					}
				}
				else if (basetype == reshade::api::format::r32_sint || basetype == reshade::api::format::r32_uint)
				{
					char ui_items[512] = ""; size_t ui_items_len = sizeof(ui_items);
					runtime->get_uniform_annotation_value(it->variable_index, "ui_items", ui_items, &ui_items_len);

					if (ui_items_len != 0)
					{
						size_t pos = 0;
						for (unsigned int k = 0; ui_items_len > pos && k != it->after.as_uint[0];)
							if (ui_items[pos++] == '\0')
								++k;

						str.append(s.data(), ::_snprintf(s.data(), s.size(), " %+lld (%s)", static_cast<int64_t>(it->after.as_uint[i]) - static_cast<int64_t>(it->before.as_uint[i]), ui_items + pos));
					}
					else if (basetype == reshade::api::format::r32_sint)
						str.append(s.data(), ::_snprintf(s.data(), s.size(), " %c %+lld (%d)", (strcmp(ui_type, "color") == 0 ? "RGBA" : "XYZW")[i], static_cast<int64_t>(it->after.as_int[i]) - static_cast<int64_t>(it->before.as_int[i]), it->after.as_int[i]));
					else
						str.append(s.data(), ::_snprintf(s.data(), s.size(), " %c %+lld (%u)", (strcmp(ui_type, "color") == 0 ? "RGBA" : "XYZW")[i], static_cast<int64_t>(it->after.as_uint[i]) - static_cast<int64_t>(it->before.as_uint[i]), it->after.as_uint[i]));
				}
				else if (basetype == reshade::api::format::r32_typeless)
				{
					if (strcmp(ui_type, "combo") == 0)
						str += it->after.as_bool ? " On" : " Off";
					else
						str += it->after.as_bool ? " True" : " False";
				}
			}
		}

		str.append(2, '#').append(std::to_string(position));
		if (ImGui::Selectable(str.c_str(), position == ctx._history_position))
		{
			modified = true;
			selection = position;
		}
		str.clear();

		if (ctx._history_updated && position == ctx._history_position)
			ctx._history_updated = false, ImGui::SetScrollHereY();
	}

	if (selection == std::numeric_limits<size_t>::max())
		return;
	else if (selection == ctx._history_position)
		return;

	auto it = std::next(ctx._histories.begin(), ctx._history_position);
	ptrdiff_t distance = static_cast<ptrdiff_t>(selection) - static_cast<ptrdiff_t>(ctx._history_position);

	ctx._history_position = selection;

	if (distance > 0)
	{
		while (distance-- > 0)
		{
			if (it->kind == history::kind::technique_switch)
			{
				runtime->set_technique_enabled(it->technique_index, !it->technique_enabled);
			}
			else
			{
				reshade::api::format basetype;
				runtime->get_uniform_variable_type(it->variable_index, &basetype);

				switch (basetype)
				{
				case reshade::api::format::r32_typeless:
					runtime->set_uniform_value(it->variable_index, &it->before.as_bool, 1);
					break;
				case reshade::api::format::r32_sint:
					runtime->set_uniform_value(it->variable_index, it->before.as_int, 16);
					break;
				case reshade::api::format::r32_uint:
					runtime->set_uniform_value(it->variable_index, it->before.as_uint, 16);
					break;
				case reshade::api::format::r32_float:
					runtime->set_uniform_value(it->variable_index, it->before.as_float, 16);
					break;
				}
			}

			++it;
		}
	}
	else
	{
		while (distance++ < 0)
		{
			--it;

			if (it->kind == history::kind::technique_switch)
			{
				runtime->set_technique_enabled(it->technique_index, it->technique_enabled);
			}
			else
			{
				reshade::api::format basetype;
				runtime->get_uniform_variable_type(it->variable_index, &basetype);

				switch (basetype)
				{
				case reshade::api::format::r32_typeless:
					runtime->set_uniform_value(it->variable_index, &it->after.as_bool, 1);
					break;
				case reshade::api::format::r32_sint:
					runtime->set_uniform_value(it->variable_index, it->after.as_int, 16);
					break;
				case reshade::api::format::r32_uint:
					runtime->set_uniform_value(it->variable_index, it->after.as_uint, 16);
					break;
				case reshade::api::format::r32_float:
					runtime->set_uniform_value(it->variable_index, it->after.as_float, 16);
					break;
				}
			}
		}
	}
}

extern "C" __declspec(dllexport) const char *NAME = "History Window";

BOOL APIENTRY DllMain(HMODULE hModule, DWORD fdwReason, LPVOID)
{
	switch (fdwReason)
	{
	case DLL_PROCESS_ATTACH:
		if (!reshade::register_addon(hModule))
			return FALSE;
		reshade::register_event<reshade::addon_event::init_effect_runtime>(on_init);
		reshade::register_event<reshade::addon_event::destroy_effect_runtime>(on_destroy);
		reshade::register_event<reshade::addon_event::reshade_reloaded_effects>(on_reloaded_effects);
		reshade::register_event<reshade::addon_event::reshade_set_uniform_value>(on_set_uniform_value);
		reshade::register_event<reshade::addon_event::reshade_set_technique_enabled>(on_set_technique_enabled);
		reshade::register_overlay("History", draw_history_window);
		break;
	case DLL_PROCESS_DETACH:
		reshade::unregister_addon(hModule);
		break;
	}

	return TRUE;
}
```

**Comment by seri14** [comment]
I will trying to create the addon

**Comment by crosire** [comment]
Added this to the add-on examples now (https://github.com/crosire/reshade/commit/49cfd00dc97c883aee857d952b12410ffc95c5b1, see https://github.com/crosire/reshade/tree/main/examples/06-history_window).

**Pull request closed without merging**
