### PR TITLE
Add macro of screenshot/postsavecommand %Count% and %Rotate%

### PR DESCRIPTION
**Pull request by seri14**
Users can use this macro to avoid overwriting already saved file when saving

### CODE REVIEW

**Comment by crosire** [comment]
I don't quite understand the purpose of `%Rotate%` (`%Count%` makes sense to me)?

**Comment by seri14** [comment]
`Count` is the times of screenshots, so if you replace `TimeSecond` with it, filename duplication is not occur as long as times is below the average frame rate.
In the first commit, the number of digits was 1 (supports up to 10 times per second).
https://github.com/crosire/reshade/compare/0ff75fd4508a643cab9d0881a7dc4052f64de652..c3c0f0ed1c34d853ef0bcf2461dd7aa9bfab7fe7
It might make sense than that.
Actually, the number of digits has changed by my own reason.
I developing an add-on "take screenshot repeatly for the specified number of frames".

**Comment by seri14** [comment]
High-end PCs run games at 144-240 FPS. If the user wants to take continuous screenshots for 1 second, 1 digits is not enough, 2 digits is not enough, 3 digits is little far to rotation, but enough.

**Comment by seri14** [comment]
An actual example, the game give the rotate to the screenshot name, the number of digits is 3.
`gameshortnameyyyyMMdd_HHmmss_RRR.ext` (R is Rotate)

**Pull request merged**
