### PR TITLE
Some changes to the behavior of preset saving.

### PR DESCRIPTION
**Pull request by liuxd17thu**
1. Now preset will be saved immediately after auto save is toggled on.

2. Differentiate "Save preset without cleaning" & "Save preset with cleaning". Now the behaviors are:
* Auto Save On: Clicking the button always cleans the preset and saves it.
* Auto Save Off: Clicking the button behaves the save as "auto save" (without cleaning). Use Shift + Click for a save with cleaning.

Sometimes we prefer keeping values for those optional or temporarily disabled effects. However save button always performs cleaning in earlier designs, even if auto save is disabled.

Besides, the icon is changed to `ICON_FK_REFRESH` for save without cleaning. I have not come up with a better icon so far.

### CODE REVIEW

**Comment by crosire** [comment]
I'd just leave the icon untouched

**Comment by liuxd17thu** [comment]
> I'd just leave the icon untouched

Updated.

**Comment by cot6** [comment]
This makes more confusing.
It is not clear to me why the trim is switched on/off when toggled the autosave.

**Comment by cot6** [comment]
Sorry, but the Japanese tutorial needs additional work because the explanation is outdated.

**Pull request merged**
