### PR TITLE
Add overlay registration function to allow add-on developers can localize tab text

### PR DESCRIPTION
**Pull request by cot6**
See my add-on side https://github.com/cot6/reshade-addons/commit/e4e1e76f59c7ab4085ba250dfd3b6fe37634ab37?diff=unified&w=1#diff-679e5303e1aa00dc65ab0fe1cb05cba3aa6b743a3ffd40fd2e702d3d22064ac5

### CODE REVIEW

**Comment by crosire** [comment]
This should not be needed, since imgui already uniquely identifies the overlay window based on the ID following `###`, rather than any localized text before that. And ReShade itself keeps track of overlays per add-on, so doesn't really matter if the localized text is in the map it uses.

**Comment by cot6** [comment]
> This should not be needed, since imgui already uniquely identifies the overlay window based on the ID following `###`, rather than any localized text before that. And ReShade itself keeps track of overlays per add-on, so doesn't really matter if the localized text is in the map it uses.

How to pass the `_("History###editorhistory")` in every frame?
Currently, only the DllMain function can pass the name and identifier of the tab. (Or you mean do regist and unregist on certain events?)
If user switches languages, the glyphs are out of range because the add-on cannot update the text.

**Comment by crosire** [comment]
Ah, now I see what this is solving. In that case, seems easier to me to just use the existing `reshade_overlay` event to add your window instead of the overlay registration mechanism (since the solution from this PR doesn't solve VR either, so might as well go the full control route).

**Comment by cot6** [comment]
What should I do with these logs that output every frame?
Or would you solve this issue on your side?

```log
2024-01-05T12:39:09:125 [39332] | DEBUG | Unregistered overlay with title "History###editorhistory" and callback 00007FF933082D70.
2024-01-05T12:39:09:126 [39332] | DEBUG | Unregistered overlay with title "History###editorhistory" and callback 00007FF933082D70.
2024-01-05T12:39:09:127 [39332] | DEBUG | Registered overlay with title "History###editorhistory" and callback 00007FF933082D70.
2024-01-05T12:39:09:155 [39332] | DEBUG | Unregistered overlay with title "History###editorhistory" and callback 00007FF933082D70.
2024-01-05T12:39:09:156 [39332] | DEBUG | Unregistered overlay with title "History###editorhistory" and callback 00007FF933082D70.
2024-01-05T12:39:09:157 [39332] | DEBUG | Registered overlay with title "History###editorhistory" and callback 00007FF933082D70.
2024-01-05T12:39:09:161 [39332] | ERROR | Failed to load latin font from "T:\source\repos\github\cot6\reshade-addons\deps\reshade\bin\x64\Debug\ProggyClean.ttf" with error code 2!
2024-01-05T12:39:09:256 [39332] | DEBUG | Font atlas size: 1024x4096
2024-01-05T12:39:09:283 [39332] | DEBUG | Unregistered overlay with title "History###editorhistory" and callback 00007FF933082D70.
2024-01-05T12:39:09:283 [39332] | DEBUG | Unregistered overlay with title "螻･豁ｴ###editorhistory" and callback 00007FF933082D70.
2024-01-05T12:39:09:284 [39332] | DEBUG | Registered overlay with title "螻･豁ｴ###editorhistory" and callback 00007FF933082D70.
2024-01-05T12:39:09:290 [39332] | DEBUG | Unregistered overlay with title "History###editorhistory" and callback 00007FF933082D70.
2024-01-05T12:39:09:291 [39332] | DEBUG | Unregistered overlay with title "螻･豁ｴ###editorhistory" and callback 00007FF933082D70.
2024-01-05T12:39:09:292 [39332] | DEBUG | Registered overlay with title "螻･豁ｴ###editorhistory" and callback 00007FF933082D70.
```

```cpp
static void on_reshade_overlay(reshade::api::effect_runtime *runtime)
{
    // for VR
    reshade::unregister_overlay("History###editorhistory", draw_history_window);

    // for Monitor
    reshade::unregister_overlay(_("History###editorhistory"), draw_history_window);
    reshade::register_overlay(_("History###editorhistory"), draw_history_window);
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD fdwReason, LPVOID)
{
    if (fdwReason == DLL_PROCESS_ATTACH)
    {
        if (!reshade::register_addon(hModule))
            return FALSE;

        ...

        reshade::register_event<reshade::addon_event::reshade_overlay>(on_reshade_overlay);
        reshade::register_overlay("History###editorhistory", draw_history_window);
    }
    else if (fdwReason == DLL_PROCESS_DETACH)
    {
        reshade::unregister_overlay("History###editorhistory", draw_history_window);

        ...
    }

    return TRUE;
}
```

**Comment by crosire** [comment]
The idea behind the `reshade_overlay` event is that imgui windows can be created manually, no registration with ReShade needed:
```c++
static void on_reshade_overlay(reshade::api::effect_runtime *runtime)
{
    ImGui::Begin(_("History###editorhistory"));
   ... 
    ImGui::End();
}
```

**Comment by cot6** [comment]
You said full control, does that mean not to use regist_overlay in my add-on code?

**Comment by cot6** [comment]
> The idea behind the `reshade_overlay` event is that imgui windows can be created manually, no registration with ReShade needed:
> 
> ```c++
> static void on_reshade_overlay(reshade::api::effect_runtime *runtime)
> {
>     ImGui::Begin(_("History###editorhistory"));
>    ... 
>     ImGui::End();
> }
> ```

Now I understand. I will try it.

**Comment by cot6** [comment]
This code works. Is there any way to implement the equivalent of this code in VR? (Well, I don't know how to debug this with VR.)
https://github.com/cot6/reshade-addons/commit/9f58547703d17560b58d374d2b14d14ba096f247?diff=unified&w=1

**Comment by crosire** [comment]
I wouldn't worry about VR too much, it's a niche enough use case.

**Pull request closed without merging**
